### ISSUE TITLE
date_ymd

### ISSUE THREAD

**Issue by luaneyed** [croquiscom/style-guide#12]
`date_ymd`와 관련된 규칙이 명시되어 있어야 할 것 같습니다.

**Comment by neverlish** [comment]
Graphql API  설명 중 [날짜/시간](https://github.com/croquiscom/style-guide/blob/master/API/GraphQL.md#날짜시간) 이라는 항목이 있는데, 여기를 보면 될 거 같습니다.

만약 Graphql API 가 아닌 다른 곳에서도 이 규칙이 적용되어야 한다면 항목을 옮길 필요는 있어 보이네요

**Comment by luaneyed** [comment]
db column에서도 적용해야 할까요? @sixmen

**Comment by kwangkuk0821** [comment]
날짜에는 date_xxx 가 괜찮은 것 같지만, 시간에는 단어의 의미상 좀 애매한 것 같기도 합니다.
그래서인지 컬럼이 created_at 으로 되어 있는 곳도 있었던 것 같아요.

**Comment by luaneyed** [comment]
저는 개인적으로 `created_at`, `updated_at` 파이긴 한데,

저도 date와 datetime을 변수명/컬럼명에서 분리하는 것이 좋지 않나 했지만
cormo에서 `DATE` type은 안 쓰이고 어차피 자동으로 `DATETIME`으로만 지정하고 있어서 굳이 구분 안 하는 걸로 이해하고 넘어갔던 것 같습니다.

정수형으로 저장한다는 가정 하에, `date_xxx_ymd`가 **Int column**의 이름으로는 괜찮은 편이라고 생각합니다.

**Comment by kwangkuk0821** [comment]
@luaneyed 
DATE type 은 안쓰이고, **DATETIME 으로만** 지정하고 있다면 저는 더 애매하게 느껴지는군요.

> 정수형으로 저장한다는 가정 하에, date_xxx_ymd가 Int column의 이름으로는 괜찮은 편이라고 생각합니다.

정수형으로 저장한다면 저도 나쁘진 않은 것 같습니다.

**Comment by sixmen** [comment]
API와 DB는 모두 같은 규칙을 쓰는 것으로 생각하고 있습니다.

API에 써 있는 규칙을 TypeScript 스타일 가이드나 용어 가이드 같은 곳에도 적어야 할지는 좀 더 살펴봐야 할 것 같습니다.

초기에는 Rails를 따라서 created_at, updated_at을 썼는데 그 외의 다른 데이터(예 date_last_goods_updated)에도 적용하려니 Native 가 아니여서 그런지 모르겠지만 적당한 단어처럼 보이지 않아서 date_xxx 로 정했습니다.

SQL 에서는 date, time, datetime, timestamp 가 전부 다르긴 한데, 시간만 저장할 일은 없을 것 같고, 기준 언어인 JavaScript에서는 (그리고 그 기반인 Java도) Date 클래스로 날짜/시간을 표한하고 있어서 date 라는 prefix를 사용하고 있습니다.

API 입장에서 보면 정확한 용어는 timestamp 가 맞긴 합니다. (그래서 CrTimestamp 라고 스칼라를 정의해서 사용하고 있죠)

날짜/시간 중 날짜만 저장한다고 할 때 date_ymd 가 어색하긴 한데, date가 날짜/시간 저장하는 용도로 쓰기도 했고, 20191334 처럼 말이 안 되는 날짜 값도 가질 수 있다는 뜻에서 SQL의 date와는 다른 용어를 쓰는 것도 나쁘진 않을 것 같습니다.
